notebook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from notebook import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('owners/', include(('owners.urls', 'owners'), namespace='owners')),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
]

owners/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views


urlpatterns = [
    path('login/', LoginView.as_view (template_name="login_owner.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout_page"),
    path('register_user/', views.register_user, name='register_user'),
    ]

posts/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    path('delete_note/<int:entry_id>', views.delete_note, name='delete_note'),
]

owners/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[:40] + "..."

    class Meta:
        verbose_name_plural = 'entries'

posts/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80, 'class': 'form-control'})}

owners/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.views import LogoutView
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('posts:home'))

def register_user(request):
    if request.method != 'POST':
        form = UserCreationForm
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username = new_user.username, password=request.POST['password'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('posts:home'))

    setting = {'form': form}
    return render(request, 'register_user.html', setting)

posts/views.py
from django.shortcuts import render
from .models import Topic
from .models import Entry
from django.contrib.auth.decorators import login_required


from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .forms import TopicForm, EntryForm
# Create your views here.

def home(request):
    return render(request, 'home.html')

@login_required
def topics(request):
    topics = Topic.objects.filter(user=request.user).order_by('date_added')
    setting = {'topics': topics}
    return render(request, 'topics.html', setting)


@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.user != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    setting = {'topic': topic, 'entries': entries}
    return render(request, 'topic.html', setting)


@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.user = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('posts:topics'))

    setting = {'form': form}
    return render(request, 'new_topic.html', setting)

@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('posts:topic', args=[topic_id]))

    setting = {'topic': topic, 'form': form}
    return render(request, 'new_entry.html', setting)


@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.user != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('posts:topic', args=[topic.id]))

    setting = {'entry' : entry, 'topic' : topic, 'form' : form}
    return render(request, 'edit_entry.html', setting)


@login_required
def delete_note(request, entry_id):
    note = Entry.objects.get(id=entry_id)
    topic = note.topic

    note.delete()

    return HttpResponseRedirect(reverse('posts:topic', args=[topic.id]))

owners/templates/login_owner.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap3 %}

{% block header %}

  <h3>Log in to your diary</h3>
{% endblock header %}


{% block content %}
  <form method="post" action="{% url 'owners:login' %}" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}

      {% buttons %}
      <button name="submit" class="btn btn-primary">log in</button>
      {% endbuttons %}

      <input type="hidden" name="next" value="{% url 'posts:home' %}" />
  </form>

{% endblock content %}

owners/templates/register_user.html
{% extends "base.html" %}
{% load static %}
{% block content %}

  <form method="post" action="{% url 'owners:register_user' %}">
      {% csrf_token %}
      {{ form.as_p }}

      <button name="submit">register</button>
      <input type="hidden" name="next" value="{% url 'posts:home' %}">
  </form>

{% endblock content %}

posts/templates/base.html
{% load static %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Diary</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery=1 %}
    <link type="text/css" rel="stylesheet" href="{% static 'home.css' %}">
</head>


<body>
  <nav class="navbar navbar-default navbar-static-top">
      <div class="container">

          <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed"
                 data-toggle="collapse" data-target="#navbar"
                      aria-expanded="false" aria-controls="navbar">

              </button>
              <a class="navbar-brand" href="{% url 'posts:home' %}">home page</a>
          </div>

          <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                  <li><a href="{% url 'posts:topics' %}">Topics</a></li>
              </ul>

              <ul class="nav navbar-nav navbar-right">
                  {% if user.is_authenticated %}
                  <li><a>Hello, {{ user.username }}.</a></li>
                  <li><a href="{% url 'owners:logout_page' %}">log out</a></li>
                  {% else %}
                  <li><a href="{% url 'owners:register_user' %}">register</a></li>
                  <li><a href="{% url 'owners:login' %}">log in</a></li>
                  {% endif %}
              </ul>
          </div>
      </div>
  </nav>

      <div class="container">
          <div class="page-header">
                {% block header %}{% endblock header %}
          </div>
          <div>
              {% block content %}{% endblock content %}
          </div>
      </div>

</body>
</html>

posts/templates/edit_entry.html
{% extends "base.html" %}
{% load static %}
{% block content %}

  <p><a href="{% url 'posts:topic' topic.id %}">{{ topic }}</a></p>

  <p>Edit note:</p>

  <form action="{% url 'posts:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
  </form>

{% endblock content %}

posts/templates/home.html
{% extends "base.html" %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<body>

{% block header %}
   <div class="jumbotron">
       <h1>There you can keep your secrets</h1>
   </div>
{% endblock header %}

{% block content %}
<h2>
    <a href="{% url 'owners:register_user' %}">Register your account</a> to make your own posts and save it as a memory.
</h2>
<h2>
    Whatever happened in your life, just write it down so you can keep your memories and never forget them.
</h2>
{% endblock content %}

</body>
</html>

posts/templates/new_entry.html
{% extends "base.html" %}
{% load static %}
{% block content %}

  <p><a href="{% url 'posts:topic' topic.id %}">{{ topic }}</a></p>

  <p>Add a new entry:</p>
  <form action="{% url 'posts:new_entry' topic.id %}"  method='post'>
      {% csrf_token %}
      {{ form.as_p }}
      <button name="submit">add note</button>
  </form>
{% endblock content %}

posts/templates/new_topic.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap3 %}

{% block header %}
  <h3>Add a new topic</h3>
{% endblock header %}

{% block content %}
  <form action="{% url 'posts:new_topic' %}" method="post" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
      <button name="submit" class="btn btn-primary">add title</button>
      {% endbuttons %}
  </form>
{% endblock content %}

posts/templates/topic.html
{% extends "base.html" %}
{% load static %}

{% block header %}
 <h3>{{ topic }}</h3>
{% endblock header %}


{% block content %}
    <p>
        <a href="{% url 'posts:new_entry' topic.id %}">add new note</a>
    </p>

  {% for entry in entries %}
      <div class="panel panel-default"> <div class="panel-heading">
      <h3>
          {{ entry.date_added|date:'M d, Y H:i' }}
          <small>
                    <a href="{% url 'posts:edit_entry' entry.id %}">edit note</a>
          </small>
          <small>
              {% url 'posts:delete_note' entry.id as the_url %}
              <a href="#" class="pull-right" data-toggle="modal" data-target="#deleteNoteModal"
                 onclick="updateModal('delNoteModalLink','{{the_url}}')">delete note</a>
          </small>
      </h3>
      </div>
          <div class="panel-body">
              {{ entry.text|linebreaks }}
          </div>
      </div>
  {% empty %}

          There are no entries for this topic yet.

  {% endfor %}

{% endblock content %}

posts/templates/topics.html
{% extends "base.html" %}
{% load static %}



{% block header%}
  <h1>Topics</h1>
{% endblock header %}


{% block content %}
  <ul>
      {% for topic in topics %}
        <li>
            <h3>
            <a href="{% url 'posts:topic' topic.id %}">{{ topic }}</a>
            </h3>
        </li>
      {% empty %}
        <li>No topics have been added yet</li>
      {% endfor %}
  </ul>

  <h3><a href="{% url 'posts:new_topic' %}">Add a new topic:</h3>

{% endblock content %}